# SoulBound uses MiniMessage (https://docs.adventure.kyori.net/minimessage/format.html) for formatting
# Legacy '&' tags are supported, but if at all possible MiniMessage <> tag formatting should be used.
#
# The Lore that will be added to the soul bound item. <username> here is a custom placeholder tag that will be
# replaced by the player's username
attachLoreToItem: true
keepOnDeath: true

# Prevents anvil use with bound items
blockAnvil: false

# Prevents crafting with bound items
blockCrafting: false

# Prevents enchanting with bound items
blockEnchant: false

debug: false

# This is a list of commands that a player will be prevented from using with their 
# Messages
messages:
  # The prefix appended to each message coming from the plugin
  prefix: "<dark_gray>[<aqua>Soul<dark_aqua>Bound<dark_gray>]<reset>"

  # A player tries using an anvil with a soul bound item
  denyAnvil: <blue>You are worried the results might be soul crushing -- best to not.
  # A player tries crafting with a soul bound item
  denyCraft: <blue>You don't know any recipies that involve souls
  # A player tries echanting with a soul bound item
  denyEnchant: <blue>No horcruxes for you. Stop that.
  # A player tries to interact with a soul bound item that is bound to a group they are not in
  denyGroup: "<blue> This item is soul bound"
  # A player tries to interact with a soul bound item that does not belong to them
  denyPlayer: "<blue> This item is soul bound to another player"

  errorEmptyMainHand: "You must be holding an item in your main hand"
  errorAlreadyBound: "This item is already soul bound"
  errorNotBound: "This item is not bound to anyone currently"
  errorNoSuchPlayer: "No such player found online"

  success: "<green> Soul bind complete"
  successUnbind: "<green> Soul bind broken"  
